---
- name: Install dnsdist
  package:
    name: dnsdist
    state: present

- name: Deploy dnsdist configuration
  template:
    src: dnsdist.conf.j2
    dest: /etc/dnsdist/dnsdist.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart dnsdist
  tags:
    - dnsdist-config
