all:
  vars:
    ansible_port: 22
    ansible_user: root
    ansible_python_interpreter: /usr/bin/python3

  hosts:
    node0:
      ansible_host: localhost
    lb0:
      ansible_host: localhost
  children:
    server_nodes:
      hosts:
        node0:
    client_nodes:
      hosts:
        lb0:
