---
- name: Make nftables.d directory
  file:
    path: /etc/nftables.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Deploy Load Balacner config
  template:
    src: "{{ lb_conf }}.j2"
    dest: /etc/nftables.d/lb-smuggler.conf
    mode: 0644
  changed_when: true

- name: Make smuggler load balancing service
  template:
    src: lb-smuggler.service.j2
    dest: "/etc/systemd/system/lb-smuggler.service"
    mode: 0644
    owner: root
    group: root
  changed_when: true
  notify:
    - Reload lb
