---
- name: Set Load Balacner config for client nodes
  set_fact:
    lb_conf: "client-nodes-lb.conf"
  when: "'client_nodes' in group_names"

- name: Set Load Balacner config for server nodes
  set_fact:
    lb_conf: "server-nodes-lb.conf"
  when: "'server_nodes' in group_names"

- import_tasks: lb.yml
  when: lb_conf is defined
