setACL({
'0.0.0.0/0',
'::/0'
})

newServer({address="127.0.0.1:5301", pool="ns1.domain.tld", checkName="ns1.domain.tld", checkType="NS"})
newServer({address="127.0.0.1:5302", pool="ns2.domain.tld", checkName="ns2.domain.tld", checkType="NS"})

addAction(makeRule("ns1.domain.tld"), PoolAction("ns1.domain.tld"))
addAction(makeRule("ns2.domain.tld"), PoolAction("ns2.domain.tld"))

addAction(AllRule(), DropAction())

setLocal("0.0.0.0:53")
setServerPolicy(firstAvailable)
setUDPTimeout(2)
setMaxUDPOutstanding(65535)
setTCPRecvTimeout(2)
setTCPSendTimeout(2)
