---
packages_debian:
  - curl
  - net-tools
  - dnsutils
  - iproute2
  - openssh-client
  - openssh-server
  - nftables

packages_redhat:
  - curl
  - nftables
  - iproute
  - bind-utils
  - openssh
  - net-tools
