---
load_balancing: false

lb:
  type: "hash" ## Options: hash, random, roundrobin
  ports:
    - "80"
    - "8080"
    - "8880"
    - "2052"
    - "2082"
    - "2086"
    - "2095"
    - "443"
    - "2053"
    - "2083"
    - "2087"
    - "2096"
    - "8443"
    - "9200-9400"
    - "10000-10200"

dns_load_balancing: false

dns_lb:
  type: "roundrobin" ## Options: hash, random, roundrobin
  resolvers:
    - "1.1.1.1"
    - "8.8.8.8"
    - "9.9.9.9"
