---
- name: Make SSH proxy systemd service
  template:
    src: smuggler-proxy.service.j2
    dest: /etc/systemd/system/smuggler-proxy.service
    mode: 0644
    owner: root
    group: root
  changed_when: true
