---
- name: Generate SSH keys on control node
  delegate_to: localhost
  run_once: true
  become: false
  command: >
    ssh-keygen -t ed25519 -f {{ ssh_privkey_path }} -N "" -q
  args:
    creates: "{{ ssh_privkey_path }}"

- name: Ensure .ssh directory exists
  file:
    path: "{{ ansible_user_dir }}/.ssh"
    state: directory
    mode: 0700
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Deploy private SSH key
  copy:
    content: "{{ lookup('file', ssh_privkey_path) }}"
    dest: "{{ ansible_user_dir }}/.ssh/{{ ssh_privkey }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0600
    backup: true

- name: Deploy public SSH key
  copy:
    content: "{{ lookup('file', ssh_privkey_path + '.pub') }}"
    dest: "{{ ansible_user_dir }}/.ssh/{{ ssh_privkey }}.pub"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
    backup: true

- name: Add public key to authorized_keys
  authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ lookup('file', ssh_privkey_path + '.pub') }}"
    state: present

- name: Deploy SSH proxy systemd service
  template:
    src: proxy@.service.j2
    dest: "/etc/systemd/system/proxy@{{ item.0.name }}-{{ item.1.name }}.service"
    mode: 0644
    owner: root
    group: root
  loop: "{{ smuggler_tunnels | subelements('server.proxy', skip_missing=True) }}"
  register: units_result
  tags:
    - proxy-services
  
- name: Reload systemd daemon
  systemd:
    daemon_reload: true
  when: units_result.changed
  tags:
    - proxy-services

- name: Enable and start SSH proxy services
  systemd:
    name: "proxy@{{ item.0.name }}-{{ item.1.name }}.service"
    enabled: true
    state: restarted
  loop: "{{ smuggler_tunnels | subelements('server.proxy', skip_missing=True) }}"
  tags:
    - proxy-services
