---
# DNS resolution method
# Options: "udp", "dot", "doh"
dnstt_dns_mode: "udp"                    

# DNS server to use for resolving tunnel domain
# DoH example: https://doh.domain.tld/dns-query
# DoT example: dot.domain.tld:853
# UDP example: 1.1.1.1:53
dnstt_client_resolver: "217.218.155.155:53"

# Where the client listens for connections
dnstt_client_addr: 0.0.0.0 # Listen on all interfaces
dnstt_client_port: 8080    # Port to listen on
