---
tunnels:
  - name: tun0
    client_node: lb0
    server_node: node0
    engine: dnstt
    domain: d.domain.tld
    client:
      health_check: false # Requires a local proxy to check End-to-End connection
      health_check_proxy_type: http
      health_check_proxy_addr: 127.0.0.1
      health_check_proxy_port: 10001
      health_check_max_time: 5
      health_check_connect_timeout: 3
      dns_mode: udp
      dns_resolver: "1.1.1.1:53"
      bind_addr: 0.0.0.0
      bind_port: 2052
    server:
      bind_addr: "{{ ansible_default_ipv4.address }}"
      bind_port: 53
      target_addr: 127.0.0.1
      target_port: 2052
      mtu: 493

  - name: tun1
    client_node: lb0
    server_node: node0
    engine: slipstream
    domain: d.domain.tld
    client:
      health_check: false # Requires a local proxy to check End-to-End connection
      health_check_proxy_type: socks5
      health_check_proxy_addr: 127.0.0.1
      health_check_proxy_port: 10002
      health_check_max_time: 5
      health_check_connect_timeout: 3
      dns_resolver: "1.1.1.1:53"
      bind_addr: 0.0.0.0
      bind_port: 2052
      keep_alive_interval: 200
    server:
      bind_addr: "{{ ansible_default_ipv4.address }}"
      bind_port: 53
      target_addr: 127.0.0.1
      target_port: 2052
      max_connections: 256
      

  - name: tun2
    client_node: lb0
    server_node: node0
    engine: dnstt-revived
    domain: d.domain.tld
    client:
      health_check: false # Requires a local proxy to check End-to-End connection
      health_check_proxy_type: http
      health_check_proxy_addr: 127.0.0.1
      health_check_proxy_port: 10003
      health_check_max_time: 5
      health_check_connect_timeout: 3
      dns_mode: udp
      dns_resolver: "1.1.1.1:53"
      bind_addr: 0.0.0.0
      bind_port: 2052
      max_num_labels: 2
      max_qname_len: 101
      rps: 0
      udp_workers: 100
      loglevel: "warning"
    server:
      bind_addr: "{{ ansible_default_ipv4.address }}"
      bind_port: 53
      target_addr: 127.0.0.1
      target_port: 2052
      mtu: 493
      loglevel: "warning"
