---
tunnels:
  - name: t0
    client_node: lb0
    server_node: node0
    engine: slipstream
    domain: s.domain.tld

  - name: t1
    client_node: lb0
    server_node: node1
    engine: dnstt
    domain: d.domain.tld

  - name: tun0
    client_node: lb0
    server_node: node0
    engine: dnstt
    domain: d.domain.tld
    client:
      lb:
        enabled: false
        backup_addr: 127.0.0.1
        backup_port: 2053
      health_check:
        enabled: true
        interval: "3s"
        proxy_type: http 
        proxy_addr: 127.0.0.1
        proxy_port: 2052
        test_url: "http://www.google.com/gen_204"
        timeout: 5
      dns_protocol: udp # udp, doh, dot
      dns_resolver: "1.1.1.1:53"
      bind_addr: 0.0.0.0
      bind_port: 2052
    server:
      bind_addr: "{{ ansible_default_ipv4.address }}"
      bind_port: 53
      target_addr: 127.0.0.1
      target_port: 2052
      mtu: 493
      proxy:
        - name: p1
          remote_host: 127.0.0.1
          remote_port: 22

  - name: tun1
    client_node: lb0
    server_node: node0
    engine: slipstream
    domain: d.domain.tld
    client:
      lb:
        enabled: false
        backup_addr: 127.0.0.1
        backup_port: 2053
      health_check:
        enabled: true
        interval: "3s"
        proxy_type: http 
        proxy_addr: 127.0.0.1
        proxy_port: 2052
        test_url: "http://www.google.com/gen_204"
        timeout: 5
      dns_resolver:
        - "1.1.1.1:53"
        - "8.8.8.8:53"
        - "9.9.9.9:53"
      bind_addr: 0.0.0.0
      bind_port: 2052
      keep_alive_interval: 200
    server:
      bind_addr: "{{ ansible_default_ipv4.address }}"
      bind_port: 53
      target_addr: 127.0.0.1
      target_port: 2052
      max_connections: 256
      idle_timeout_seconds: 3
      proxy:
        - name: p1
          remote_host: 127.0.0.1
          remote_port: 22
