# tunnels:
#   - name: tun0
#     client_node: lb0
#     server_node: node0
#     domain: t.domain.tld
#     client:
#       dns_mode: udp
#       dns_resolver: "85.185.157.2:53"
#       bind_addr: 0.0.0.0
#       bind_port: 2052
#     server:
#       bind_addr: "{{ ansible_default_ipv4.address }}"
#       bind_port: 53
#       forward_addr: 127.0.0.1
#       forward_port: 2052
#       mtu: 1232
