---
tunnels:
  - name: t00
    server_node: node0
    client_node: lb0
    engine: vaydns
    domain: t0.example.com
    client:
      lb:
        enabled: true
        backup_addr: 127.0.0.1
        backup_port: 2051
      health_check:
        enabled: true
        interval: "5s"
        timeout: 3
        retries: 2
        proxy_type: socks5h
        # proxy_user: hello
        # proxy_pass: world
        proxy_addr: 127.0.0.1
        proxy_port: 2050
        test_url: "http://www.google.com/gen_204"
      log_level: warn
      udp_workers: 200
      udp_timeout: 200ms
      open_stream_timeout: 10s
      reconnect_max: 30s
      reconnect_min: 1s
      session_check_interval: 500ms
      udp_shared_socket: false
      udp_accept_errors: false
      idle_timeout: 10s
      keepalive: 2s
      max_streams: 0
      max_qname_len: 101
      max_num_labels: 2
      rps: 500
      dns_protocol: udp
      dns_resolver: "127.0.0.1:5300"
      bind_addr: 127.0.0.1
      bind_port: 2050
    server:
      killer:
        enabled: true
        interval: 30min
      bind_addr: 127.0.0.1
      bind_port: 8200
      target_addr: 127.0.0.1
      target_port: 1081
      idle_timeout: 10s
      keepalive: 2s
      mtu: 493

  - name: t01
    server_node: node0
    client_node: lb0
    engine: vaydns
    domain: t1.example.com
    client:
      lb:
        enabled: true
        backup_addr: 127.0.0.1
        backup_port: 2050
      health_check:
        enabled: true
        interval: "5s"
        timeout: 3
        retries: 2
        proxy_type: socks5h
        # proxy_user: hello
        # proxy_pass: world
        proxy_addr: 127.0.0.1
        proxy_port: 2051
        test_url: "http://www.google.com/gen_204"
      log_level: warn
      udp_workers: 200
      udp_timeout: 200ms
      open_stream_timeout: 10s
      reconnect_max: 30s
      reconnect_min: 1s
      session_check_interval: 500ms
      udp_shared_socket: false
      udp_accept_errors: false
      idle_timeout: 10s
      keepalive: 2s
      max_streams: 0
      max_qname_len: 101
      max_num_labels: 2
      rps: 500
      dns_protocol: udp
      dns_resolver: "127.0.0.1:5300"
      bind_addr: 127.0.0.1
      bind_port: 2051
    server:
      killer:
        enabled: true
        interval: 30min
      bind_addr: 127.0.0.1
      bind_port: 8201
      target_addr: 127.0.0.1
      target_port: 1081
      idle_timeout: 10s
      keepalive: 2s
      mtu: 493

  - name: t10
    server_node: node0
    client_node: lb0
    engine: slipstream
    domain: t2.example.com
    client:
      lb:
        enabled: true
        backup_addr: 127.0.0.1
        backup_port: 2053
      health_check:
        enabled: true
        interval: "5s"
        timeout: 3
        retries: 2
        proxy_type: socks5h
        # proxy_user: hello
        # proxy_pass: world
        proxy_addr: 127.0.0.1
        proxy_port: 2052
        test_url: "http://www.google.com/gen_204"
      dns_resolver: "127.0.0.1:5300"
      bind_addr: 127.0.0.1
      bind_port: 2052
      keep_alive_interval: 200
    server:
      killer:
        enabled: true
        interval: 30min
      bind_addr: 127.0.0.1
      bind_port: 8202
      target_addr: 127.0.0.1
      target_port: 1081
      max_connections: 8192
      idle_timeout_seconds: 60

  - name: t11
    server_node: node0
    client_node: lb0
    engine: slipstream
    domain: t3.example.com
    client:
      lb:
        enabled: true
        backup_addr: 127.0.0.1
        backup_port: 2052
      health_check:
        enabled: true
        interval: "5s"
        timeout: 3
        retries: 2
        proxy_type: socks5h
        # proxy_user: hello
        # proxy_pass: world
        proxy_addr: 127.0.0.1
        proxy_port: 2053
        test_url: "http://www.google.com/gen_204"
      dns_resolver: "127.0.0.1:5300"
      bind_addr: 127.0.0.1
      bind_port: 2053
      keep_alive_interval: 200
    server:
      killer:
        enabled: true
        interval: 30min
      bind_addr: 127.0.0.1
      bind_port: 8203
      target_addr: 127.0.0.1
      target_port: 1081
      max_connections: 8192
      idle_timeout_seconds: 60

  - name: t20
    server_node: node0
    client_node: lb0
    engine: dnstt
    domain: t4.example.com
    client:
      lb:
        enabled: true
        backup_addr: 127.0.0.1
        backup_port: 2055
      health_check:
        enabled: true
        interval: "5s"
        timeout: 3
        retries: 2
        proxy_type: socks5h
        # proxy_user: hello
        # proxy_pass: world
        proxy_addr: 127.0.0.1
        proxy_port: 2054
        test_url: "http://www.google.com/gen_204"
      dns_protocol: udp
      dns_resolver: "127.0.0.1:5300"
      bind_addr: 127.0.0.1
      bind_port: 2054
    server:
      killer:
        enabled: true
        interval: 30min
      bind_addr: 127.0.0.1
      bind_port: 8204
      target_port: 1081
      mtu: 493

  - name: t21
    server_node: node0
    client_node: lb0
    engine: dnstt
    domain: t5.example.com
    client:
      lb:
        enabled: true
        backup_addr: 127.0.0.1
        backup_port: 2054
      health_check:
        enabled: true
        interval: "5s"
        timeout: 3
        retries: 2
        proxy_type: socks5h
        # proxy_user: hello
        # proxy_pass: world
        proxy_addr: 127.0.0.1
        proxy_port: 2055
        test_url: "http://www.google.com/gen_204"
      dns_protocol: udp
      dns_resolver: "127.0.0.1:5300"
      bind_addr: 127.0.0.1
      bind_port: 2055
    server:
      killer:
        enabled: true
        interval: 30min
      bind_addr: 127.0.0.1
      bind_port: 8205
      target_addr: 127.0.0.1
      target_port: 1081
      mtu: 493
