---
controller_keys_path: "{{ lookup('env','HOME') }}/.smuggler"
keys_path: "/opt"

dnstt_client_binary_url: "https://github.com/net2share/dnstt/releases/download/latest/dnstt-client-linux-amd64"
dnstt_pubkey: "dnstt.pub"
dnstt_privkey: "dnstt.key"

vaydns_client_binary_url: "https://github.com/net2share/vaydns/releases/download/v0.2.4/vaydns-client-linux-amd64"
vaydns_pubkey: "vaydns.pub"
vaydns_privkey: "vaydns.key"

slipstream_client_binary_url: "https://github.com/net2share/slipstream-rust-build/releases/download/v2026.02.22.1/slipstream-client-linux-amd64"
