---
# load_balancing: true

# lb:
#   type: "random" ## Options: hash, random, roundrobin
#   ports:
#     - "8080"
#     - "10000-10200"

# dns_load_balancing: true

# dns_lb:
#   type: roundrobin ## Options: hash, random, roundrobin
#   resolvers:
#     - "1.1.1.1"
#     - "8.8.8.8"
#     - "9.9.9.9"
