---
- name: Download dnstt-server binary
  get_url:
    url: "https://github.com/0xAFz/dnstt/releases/download/latest/dnstt-server-linux-amd64"
    dest: /usr/local/bin/dnstt-server
    mode: 0755
  tags:
    - dnstt-server-binary

- name: Ensure smuggler directory exists on controller
  file:
    path: "{{ controller_keys_path }}"
    state: directory
    mode: 0700
  delegate_to: localhost
  become: false
  tags:
    - dnstt-keys

- name: Check dnstt keys on controller
  stat:
    path: "{{ controller_keys_path }}/{{ dnstt_privkey }}"
  register: dnstt_keys
  delegate_to: localhost
  become: false
  tags:
    - dnstt-keys

- name: Generate dnstt keys
  shell: |
    dnstt-server -gen-key -privkey-file {{ keys_path }}/{{ dnstt_privkey }} -pubkey-file {{ keys_path }}/{{ dnstt_pubkey }}
  when: not dnstt_keys.stat.exists
  throttle: 1  # Only one at a time
  tags:
    - dnstt-keys

- name: Fetch dnstt keys to localhost
  fetch:
    src: "{{ item }}"
    dest: "{{ controller_keys_path }}/{{ item | basename }}"
    flat: true
  loop:
    - "{{ keys_path }}/{{ dnstt_privkey }}"
    - "{{ keys_path }}/{{ dnstt_pubkey }}"
  when: not dnstt_keys.stat.exists
  throttle: 1  # Only one at a time
  tags:
    - dnstt-keys

- name: Copy dnstt privkey
  copy:
    src: "{{ controller_keys_path }}/{{ dnstt_privkey }}"
    dest: "{{ keys_path }}/{{ dnstt_privkey }}"
    mode: 0600
  tags:
    - dnstt-keys

- name: Copy dnstt pubkey
  copy:
    src: "{{ controller_keys_path }}/{{ dnstt_pubkey }}"
    dest: "{{ keys_path }}/{{ dnstt_pubkey }}"
    mode: 0644
  tags:
    - dnstt-keys
