---
- import_tasks: dnstt.yml
  when: smuggler_engines | intersect(['dnstt', 'dnstt-revived']) | length > 0

- import_tasks: slipstream.yml
  when: smuggler_engines | intersect(['slipstream']) | length > 0

- name: Make systemd unit file for each tunnel
  template:
    src: smuggler@.service.j2
    dest: "/etc/systemd/system/smuggler@{{ tun.name }}.service"
    mode: 0644
    owner: root
    group: root
  loop: "{{ smuggler_tunnels }}"
  loop_control:
    loop_var: tun
  tags:
    - server-tunnels

- name: Reload systemd
  systemd:
    daemon_reload: true
  changed_when: true
  tags:
    - server-tunnels

- name: Enable and start tunnel services
  systemd:
    name: "smuggler@{{ tun.name }}"
    enabled: true
    state: restarted
  loop: "{{ smuggler_tunnels }}"
  loop_control:
    loop_var: tun
  tags:
    - server-tunnels
