---
- name: Copy dnstt-server
  copy:
    src: dnstt-server
    dest: /usr/local/bin/dnstt-server
    mode: 0755

- name: Generate keypair if not exists
  command: >
    dnstt-server -gen-key -privkey-file {{ keys_path }}/{{ tun.name }}.key -pubkey-file {{ keys_path }}/{{ tun.name }}.pub
  args:
    creates: "{{ keys_path }}/{{ tun.name }}.key"
  loop: "{{ tuns }}"
  loop_control:
    loop_var: tun

- name: Fetch server public key
  fetch:
    src: "{{ keys_path }}/{{ tun.name }}.pub"
    dest: "/tmp/{{ tun.name }}.pub"
    flat: true
  loop: "{{ tuns }}"
  loop_control:
    loop_var: tun

- name: Make systemd unit file for each tunnel
  template:
    src: smuggler@.service.j2
    dest: "/etc/systemd/system/smuggler@{{ tun.name }}.service"
    mode: 0644
    owner: root
    group: root
  loop: "{{ tuns }}"
  loop_control:
    loop_var: tun
  changed_when: true

- name: Reload systemd
  systemd:
    daemon_reload: true
  changed_when: true

- name: Enable and start tunnel services
  systemd:
    name: "smuggler@{{ tun.name }}"
    enabled: true
    state: restarted
  loop: "{{ tuns }}"
  loop_control:
    loop_var: tun
  changed_when: true
