---
- name: Ensure smuggler directory exists on controller
  file:
    path: "{{ controller_keys_path }}"
    state: directory
    mode: 0700
  delegate_to: localhost
  become: false
  run_once: true
  tags:
    - dnstt-keys
    - slipstream-keys

- import_tasks: dnstt.yml
  when: smuggler_engines | intersect(['dnstt']) | length > 0
  tags:
    - dnstt-server

- import_tasks: slipstream.yml
  when: smuggler_engines | intersect(['slipstream']) | length > 0
  tags:
    - slipstream-server

- name: Deploy killer services
  template:
    src: killer-smuggler@.service.j2
    dest: "/etc/systemd/system/killer-smuggler@{{ tun.name }}.service"
    mode: 0644
    owner: root
    group: root
  loop: "{{ smuggler_tunnels }}"
  loop_control:
    loop_var: tun
  when: tun.server.killer.enabled | default(false) | bool
  tags:
    - server-killers

- name: Deploy killer timers
  template:
    src: killer-smuggler@.timer.j2
    dest: "/etc/systemd/system/killer-smuggler@{{ tun.name }}.timer"
    mode: 0644
    owner: root
    group: root
  loop: "{{ smuggler_tunnels }}"
  loop_control:
    loop_var: tun
  when: tun.server.killer.enabled | default(false) | bool
  tags:
    - server-killers

- name: Deploy tunnel systemd services
  template:
    src: smuggler@.service.j2
    dest: "/etc/systemd/system/smuggler@{{ tun.name }}.service"
    mode: 0644
    owner: root
    group: root
  loop: "{{ smuggler_tunnels }}"
  loop_control:
    loop_var: tun
  tags:
    - server-tunnels

- name: Reload systemd daemon
  systemd:
    daemon_reload: true
  changed_when: true
  tags:
    - server-killers
    - server-tunnels

- name: Enable and start tunnel services
  systemd:
    name: "smuggler@{{ tun.name }}"
    enabled: true
    state: restarted
  loop: "{{ smuggler_tunnels }}"
  loop_control:
    loop_var: tun
  tags:
    - server-tunnels

- name: Enable and start killer timers
  systemd:
    name: "killer-smuggler@{{ tun.name }}.timer"
    enabled: true
    state: restarted
  loop: "{{ smuggler_tunnels }}"
  loop_control:
    loop_var: tun
  when: tun.server.killer.enabled | default(false) | bool
  tags:
    - server-killers
