---
- name: Copy slipstream-server
  copy:
    src: slipstream-server
    dest: /usr/local/bin/slipstream-server
    mode: 0755
  tags:
    - slipstream-server-binary

- name: Install openssl
  package:
    name: openssl
    state: present

- name: Detect mimalloc package
  shell: |
    apt-cache search '^libmimalloc[0-9]' | awk '{ print $1 }' | head -n1
  register: mimalloc_pkg
  changed_when: false
  when: slipstream_mimalloc and ansible_os_family == "Debian"

- name: Install mimalloc
  apt:
    name: "{{ mimalloc_pkg.stdout }}"
    state: present
    update_cache: true
  when: slipstream_mimalloc and ansible_os_family == "Debian"

- name: Detect mimalloc path
  shell: ldconfig -p | grep mimalloc | awk '{ print $NF }'
  register: mimalloc_path
  changed_when: false
  when: slipstream_mimalloc

- name: Fail if mimalloc not found
  fail:
    msg: "mimalloc not found"
  when: slipstream_mimalloc and mimalloc_path.stdout == ""

- name: Check if slipstream keys exists
  stat:
    path: "/tmp/{{ slipstream_privkey }}"
  register: slipstream_keys
  delegate_to: localhost
  run_once: true
  become: false
  tags:
    - slipstream-keys

- name: Generate and fetch slipstream keys
  when: not slipstream_keys.stat.exists
  run_once: true
  block:
    - name: Generate slipstream keys
      shell: |
        openssl req -x509 -newkey rsa:2048 -nodes -keyout {{ keys_path }}/{{ slipstream_privkey }} -out {{ keys_path }}/{{ slipstream_pubkey }} -days 365 -subj "/CN=slipstream"

    - name: Fetch slipstream keys to localhost
      fetch:
        src: "{{ item }}"
        dest: "/tmp/{{ item | basename }}"
        flat: true
      loop:
        - "{{ keys_path }}/{{ slipstream_privkey }}"
        - "{{ keys_path }}/{{ slipstream_pubkey }}"
  tags:
    - slipstream-keys

- name: Copy slipstream pubkey
  copy:
    src: "/tmp/{{ slipstream_pubkey }}"
    dest: "{{ keys_path }}/{{ slipstream_pubkey }}"
    mode: 0600
  when: slipstream_keys.stat.exists
  tags:
    - slipstream-keys

- name: Copy slipstream privkey
  copy:
    src: "/tmp/{{ slipstream_privkey }}"
    dest: "{{ keys_path }}/{{ slipstream_privkey }}"
    mode: 0600
  when: slipstream_keys.stat.exists
  tags:
    - slipstream-keys
