---
- name: Install base packages
  apt:
    name: "{{ packages_debian }}"
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Install base packages
  dnf:
    name: "{{ packages_redhat }}"
    state: latest
  when: ansible_os_family == "RedHat"

- name: Enable nftables
  systemd:
    name: nftables
    enabled: true
    state: restarted
    daemon_reload: true
