---
- name: Copy dnstt-client
  copy:
    src: dnstt-client
    dest: /usr/local/bin/dnstt-client
    mode: 0755
  when: "'dnstt' in smuggler_engines"
  tags:
    - dnstt-client-binary

- name: Copy dnstt-revived-client
  copy:
    src: dnstt-revived-client
    dest: /usr/local/bin/dnstt-revived-client
    mode: 0755
  when: "'dnstt-revived' in smuggler_engines"
  tags:
    - dnstt-revived-client-binary

- name: Copy dnstt public key
  copy:
    src: "/tmp/{{ dnstt_pubkey }}"
    dest: "{{ keys_path }}/{{ dnstt_pubkey }}"
    mode: 0600
  tags:
    - dnstt-keys
