---
- name: Download dnstt-client binary
  get_url:
    url: "{{ dnstt_client_binary_url }}"
    dest: /usr/local/bin/dnstt-client
    mode: 0755
  tags:
    - dnstt-client-binary

- name: Copy dnstt public key
  copy:
    src: "{{ controller_keys_path }}/{{ dnstt_pubkey }}"
    dest: "{{ keys_path }}/{{ dnstt_pubkey }}"
    mode: 0644
  tags:
    - dnstt-keys
