---
- name: Copy dnstt-client
  copy:
    src: dnstt-client
    dest: /usr/local/bin/dnstt-client
    mode: 0755
  when: "'dnstt' in smuggler_engines"

- name: Copy slipstream-client
  copy:
    src: slipstream-client
    dest: /usr/local/bin/slipstream-client
    mode: 0755
  when: "'slipstream' in smuggler_engines"

- name: Copy dnstt-revived-client
  copy:
    src: dnstt-revived-client
    dest: /usr/local/bin/dnstt-revived-client
    mode: 0755
  when: "'dnstt-revived' in smuggler_engines"

- name: Copy dnstt shared public key to client node
  copy:
    src: "/tmp/{{ dnstt_pubkey }}"
    dest: "{{ keys_path }}/{{ dnstt_pubkey }}"
    mode: 0600
  when: smuggler_engines | intersect(['dnstt', 'dnstt-revived']) | length > 0

- name: Make health check script for each tunnel
  template:
    src: health-smuggler.sh.j2
    dest: "/opt/health-smuggler-{{ tun.name }}.sh"
    mode: 0755
    owner: root
    group: root
  loop: "{{ smuggler_tunnels }}"
  loop_control:
    loop_var: tun
  when: tun.client.health_check | default(false) | bool
  changed_when: true
  tags:
    - client-tunnels

- name: Make health check service for each tunnel
  template:
    src: health@.service.j2
    dest: "/etc/systemd/system/health-smuggler@{{ tun.name }}.service"
    mode: 0644
    owner: root
    group: root
  loop: "{{ smuggler_tunnels }}"
  loop_control:
    loop_var: tun
  when: tun.client.health_check | default(false) | bool
  changed_when: true
  tags:
    - client-tunnels

- name: Make health check timer for each tunnel
  template:
    src: health@.timer.j2
    dest: "/etc/systemd/system/health-smuggler@{{ tun.name }}.timer"
    mode: 0644
    owner: root
    group: root
  loop: "{{ smuggler_tunnels }}"
  loop_control:
    loop_var: tun
  when: tun.client.health_check | default(false) | bool
  changed_when: true
  tags:
    - client-tunnels

- name: Make systemd service for each tunnel
  template:
    src: smuggler@.service.j2
    dest: "/etc/systemd/system/smuggler@{{ tun.name }}.service"
    mode: 0644
    owner: root
    group: root
  loop: "{{ smuggler_tunnels }}"
  loop_control:
    loop_var: tun
  changed_when: true
  tags:
    - client-tunnels

- name: Reload systemd
  systemd:
    daemon_reload: true
  changed_when: true
  tags:
    - client-tunnels

- name: Enable and start tunnel services
  systemd:
    name: "smuggler@{{ tun.name }}"
    enabled: true
    state: restarted
  loop: "{{ smuggler_tunnels }}"
  loop_control:
    loop_var: tun
  changed_when: true
  tags:
    - client-tunnels

- name: Enable and start health check timers
  systemd:
    name: "health-smuggler@{{ tun.name }}.timer"
    enabled: true
    state: restarted
  loop: "{{ smuggler_tunnels }}"
  loop_control:
    loop_var: tun
  when: tun.client.health_check | default(false) | bool
  changed_when: true
  tags:
    - client-tunnels
