---
- name: Copy dnstt-client
  copy:
    src: dnstt-client
    dest: /usr/local/bin/dnstt-client
    mode: 0755

- name: Copy public shared key to client node
  copy:
    src: "/tmp/{{ shared_pubkey }}"
    dest: "{{ keys_path }}/{{ shared_pubkey }}"
    mode: "0600"

- name: Make systemd unit file for each tunnel
  template:
    src: smuggler@.service.j2
    dest: "/etc/systemd/system/smuggler@{{ tun.name }}.service"
    mode: 0644
    owner: root
    group: root
  loop: "{{ tuns }}"
  loop_control:
    loop_var: tun
  changed_when: true

- name: Reload systemd
  systemd:
    daemon_reload: true
  changed_when: true

- name: Enable and start tunnel services
  systemd:
    name: "smuggler@{{ tun.name }}"
    enabled: true
    state: restarted
  loop: "{{ tuns }}"
  loop_control:
    loop_var: tun
  changed_when: true
