---
- name: Copy slipstream-client
  copy:
    src: slipstream-client
    dest: /usr/local/bin/slipstream-client
    mode: 0755
  when: "'slipstream' in smuggler_engines"
  tags:
    - slipstream-client-binary

- name: Detect mimalloc package
  shell: |
    apt-cache search '^libmimalloc[0-9]' | awk '{ print $1 }' | head -n1
  register: mimalloc_pkg
  changed_when: false
  when: slipstream_mimalloc and ansible_os_family == "Debian"

- name: Install mimalloc
  apt:
    name: "{{ mimalloc_pkg.stdout }}"
    state: present
    update_cache: true
  when: slipstream_mimalloc and ansible_os_family == "Debian"

- name: Detect mimalloc path
  shell: ldconfig -p | grep mimalloc | awk '{ print $NF }'
  register: mimalloc_path
  changed_when: false
  when: slipstream_mimalloc
  tags:
    - client-tunnels

- name: Fail if mimalloc not found
  fail:
    msg: "mimalloc not found"
  when: slipstream_mimalloc and mimalloc_path.stdout == ""
  tags:
    - client-tunnels
