---
- hosts: client_nodes
  become: true
  pre_tasks:
    - name: Filter tunnels for this host
      set_fact:
        tuns: "{{ tunnels | selectattr('client_node', 'equalto', inventory_hostname) | list }}"
        tuns_length: "{{ tunnels | selectattr('client_node', 'equalto', inventory_hostname) | list | length }}"
      tags: always
  roles:
    - { role: common, tags: common }
    - { role: client, tags: client }
    - { role: sysctl, tags: sysctl }
    - { role: tc, tags: tc, when: tc_enabled }
    - { role: lb, tags: lb, when: lb_enabled }
