---
- hosts: server_nodes
  become: true
  pre_tasks:
    - name: Filter tunnels
      set_fact:
        smuggler_tunnels: "{{ tunnels | selectattr('server_node', 'equalto', inventory_hostname) | list }}"
        smuggler_tunnels_length: "{{ tunnels | selectattr('server_node', 'equalto', inventory_hostname) | list | length }}"
      tags: always

    - name: Filter engines
      set_fact:
        smuggler_engines: "{{ smuggler_tunnels | map(attribute='engine') | unique | list }}"
      tags: always

  roles:
    - { role: server, tags: server }
    - { role: proxy, tags: proxy, when: ssh_proxy }
