---
- name: Make dnstt rate script
  template:
    src: rate.sh.j2
    dest: /opt/rate.sh
    mode: 0755
    owner: root
    group: root

- name: Make dnstt rate service
  template:
    src: rate.service.j2
    dest: /etc/systemd/system/rate.service
    mode: 0644
    owner: root
    group: root
  changed_when: true
  notify:
    - Enable rate
